name: RLsite
channels:
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - pytorch
  - dglteam
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - conda-forge
  - omnia
  - soumith
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5=2_gnu
  - absl-py=1.3.0
  - attrdict=2.0.1
  - biopython=1.76
  - blas=1.0=mkl
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - cryptography=38.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - decorator=5.1.1
  - dgl-cuda11.3=0.9.1post1
  - expat=2.5.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37=0
  - font-ttf-inconsolata=2.000=0
  - font-ttf-source-code-pro=2.030=0
  - font-ttf-ubuntu=0.83=0
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - grpcio=1.41.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=4.11.4
  - intel-openmp=2021.4.0
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0=12_linux64_mkl
  - libdeflate=1.14
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - libnsl=2.0.0
  - libpng=1.6.39
  - libprotobuf=3.15.8
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libuv=1.44.2
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.6
  - networkx=2.6.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openbabel=3.1.1
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.2.3
  - patsy=0.5.3
  - pcre2=10.40
  - pillow=9.2.0
  - pip=22.3.1
  - pixman=0.40.0
  - protobuf=3.15.8
  - psutil=5.9.0
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.10.0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.6
  - readline=8.1.2
  - requests=2.28.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - setuptools=59.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - statsmodels=0.13.2
  - tensorboard=1.15.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - torchaudio=0.10.0
  - torchvision=0.11.0
  - tqdm=4.56.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.13
  - werkzeug=2.2.2
  - wheel=0.38.4
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - boto3==1.28.62
    - botocore==1.31.62
    - jmespath==1.0.1
    - rnaglib==2.0.1
    - s3transfer==0.7.0

